language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    - DEPENDENCIES=lowest
    - DEPENDENCIES=highest

matrix:
  include:
    - php: 7.0
      env: COVERAGE=yes
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm && $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update

install:
  - if [ -z $DEPENDENCIES ]; then composer install -n; fi;
  - if [ $DEPENDENCIES = lowest ]; then composer update --prefer-lowest -n; fi;
  - if [ $DEPENDENCIES = highest ]; then composer update -n; fi;

script:
  - if [[ $COVERAGE = yes ]]; then bin/phpunit --verbose; else bin/phpunit --verbose --no-coverage; fi

after_script:
  - if [[ $COVERAGE = yes ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
